### PR TITLE
Remove random linebreaks, fixes #2

### LINKED ISSUE #2: Bug with linebreaks in dependencies
Parsing the [DESCRIPTION for Rcpp](https://github.com/cran/Rcpp/blob/master/DESCRIPTION#L19-L20) we get:

```
[1] "RUnit"                 "inline"                "rbenchmark"            "knitr"                 "rmarkdown"            
[6] "pinp"                  "pkgKitten\n(>= 0.1.2)"
```

Note that `pkgKitten` includes a `\n` before the version. This messes up the formatting when we insert this back into a DESCRIPTION file. 

Another case is `dbplyr` which includes `rlang (>=\n0.2.0)` as a dependency.

### PR DESCRIPTION
**Pull request by jeroen**
I think this is the simplest solution. I don't think it's worth it introducing options just for this, because this requires changing all the function signatures.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
TBH this seems a bit harsh, we _might_ have fields where newlines are significant... strictly speaking it is already significant in fields that have R code, e.g. `Authors@R`. Not that this happens a lot, but why not just remove from the dependency fields?

**Comment by jeroen** [comment]
That's fine by me as well. In my experience, the whitespace are mostly meaningless dcf artifacts, so for me it's safest to strip them to prevent database mismatches due to random whitespace.

But if you like to keep only strip them for selected fields, that's fine too. The most important case is the depends fields, where the current behavior is really a bug.

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by jeroen** [comment]
I was just pushing some tests! :D

**Comment by gaborcsardi** [comment]
OK, I'll merge them manually.

**Comment by gaborcsardi** [comment]
Except you deleted the branch....

**Comment by gaborcsardi** [comment]
Oh, they were included...

**Pull request merged**
