### PR TITLE
parse built field

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I added a Travis config, can you pls rebase so that the tests run? 

Btw. can you please also add a test case? The `zip` file in `test` has a `Built` field. Thanks!

**Comment by jeroen** [comment]
OK done 👍 . PS: is it on purpose that the `.zip` package is for unix and not windows?

**Comment by gaborcsardi** [comment]
No, I just zipped it up on Unix, it should not matter too much....

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
